### ISSUE TITLE
Catch LineupOptimizerException

### ISSUE THREAD

**Issue by trevordavies095** [DimaKudosh/pydfs-lineup-optimizer#14]
What's the correct way to catch this exception? I can't for the life of me catch it.

Even this doesn't work.

```
try:
    lineup_generator = optimizer.optimize(10)
except:
    pass
```

I still get the Runtime Error 

```
pydfs_lineup_optimizer.exceptions.LineupOptimizerException: Can't generate lineups
```

**Comment by rneu31** [comment]
from pydfs_lineup_optimizer.exceptions import LineupOptimizerException

Then use the LineupOptimizerException in the except block.

Sorry I'm on my phone hope this helps some.

**Comment by ltd9938** [comment]
Nope. Still doesn't catch it. I tried that which is why I'm so confused. The blank except should also catch it.

```
try:
    lineup_generator = optimizer.optimize(10)
except LineupOptimizerException:
    pass
```

**Comment by trevordavies095** [comment]
Nope. Still doesn't catch it. I tried that which is why I'm so confused. The blank except should also catch it.

```
try:
    lineup_generator = optimizer.optimize(10)
except LineupOptimizerException:
    pass
```

**Comment by DimaKudosh** [comment]
You didn't catch exception because optimize is a generator, so when you call optimize it doesn't run optimizer immediately, it starts working after you start iterations. So if you want to get all optimized lineups together you can write this:
```
try:
    lineups = list(optimizer.optimize(10))
except LineupOptimizerException:
    pass
```
And exception will be caught because list forces evaluation of lineups and converting it to list. Or you can write this:
```
try:
    for lineup in optimizer.optimize(10):
        print(lineup)
except LineupOptimizerException:
    pass
```
It will create lineups by one. It's done in a such way because creating many lineups with many constraints can take a lot of time, and with generator you can start processing new lineup after creation and don't wait until all lineups will be created.

**Comment by ltd9938** [comment]
Perfect! I feel like an idiot. 

Thank you!

**Comment by trevordavies095** [comment]
Perfect! I feel like an idiot. 

Thank you!
