### ISSUE TITLE
Late-swap Feature

### ISSUE THREAD

**Issue by pippinainteasy** [DimaKudosh/pydfs-lineup-optimizer#178]
I have just started working with the late-swap feature and was wondering, what would cause a `Player not found in players pool` exception after the first games lock?

**Comment by DimaKudosh** [comment]
You should run both these methods in this order before using this feature:
```
optimizer.load_players_from_csv(csv_filename)
lineups = optimizer.load_lineups_from_csv(csv_filename)
```

**Comment by pippinainteasy** [comment]
So for reference is this syntax not correct?

`def draftkings_lateswap():`

    csv_filename = "DKEntries.csv"
    optimizer = get_optimizer(Site.DRAFTKINGS, Sport.BASKETBALL)
    optimizer.load_players_from_csv(csv_filename)
    lineups = optimizer.load_lineups_from_csv(csv_filename)

**Comment by bimpyinu** [comment]
The bug seems to stem from the playerid parsing for lateswap - it includes the closing playerid parantheses for players who are marked with the tag " (LOCKED)" when it's trying to find the playerid, and removing the closing parantheses from these players allows the feature to work as expected. I'll attach examples of what I mean in case that was not clear.


[Live Entries Example.xlsx](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/5069542/Live.Entries.Example.xlsx)
[Live Entries Example Fixed.xlsx](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/5069543/Live.Entries.Example.Fixed.xlsx)

**Comment by mbencho** [comment]
tried the Fixed example there and was still getting the same error

**Comment by DimaKudosh** [comment]
Fixed bug with incorrect player id parsing in version 3.4.0
