### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by GeorgeMcIntire** [DimaKudosh/pydfs-lineup-optimizer#22]
I get this when I try to upload a CSV file of the players' information.

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 1727: invalid continuation byte`

**Comment by DimaKudosh** [comment]
Seems that your csv has another encoding and can't be parsed with `load_players_from_csv` function, because it accepts csv with utf-8 encoding. I think you should write your own csv parser instead for this and then register it for site you using. Here you can see source code for example: [https://github.com/DimaKudosh/pydfs-lineup-optimizer/blob/master/pydfs_lineup_optimizer/sites/draftkings/importer.py](https://github.com/DimaKudosh/pydfs-lineup-optimizer/blob/master/pydfs_lineup_optimizer/sites/draftkings/importer.py).
