### ISSUE TITLE
Restrict/stack in captain mode

### ISSUE THREAD

**Issue by holmes72** [DimaKudosh/pydfs-lineup-optimizer#230]
With DK captain mode there are only two Roster Positions (CPT and FLEX) and my lines end up with questionable combinations.  The salary download also includes actual position, but I don't think this is taken into account by the optimizer.  Is there a method to exclude player combinations (restrict Rothlisberger/Bengals combination) or stack/restrict based on actual position (restrict opposing team QB/DST, stack QB/WR).

**Comment by sansbacon** [comment]
There is no way to do this directly. I would just filter your lineups in a post-optimization step. Note that the optimizer is a generator so you can set the initial number of lineups to a high number.

```
n_wanted_lineups = 25
wanted_lineups = []

def meets_criteria(lineup):
    """Defines criteria for lineup"""
    pass

for lineup in optimizer.optimize(500):
    if meets_criteria(lineup):
        wanted_lineups.append(lineup)
    if len(wanted_lineups) == n_wanted_lineups:
        break
```

Another way to accomplish this goal is to have multiple projection sets based on your assumptions on how the game is going to go. For example, if the QB has a good game, then the opposing DST is less likely to have a good game, so your projections for a particular set of circumstances should adjust these values accordingly. This may be a superior approach to "no QB vs DST" because, in certain circumstances, the projections may justify this combination of players and your rule against it prevents you from finding the optimal lineup.

```
lineups_per_projection_set = 10
wanted_lineups = []
projection_sets = [set1, set3, ...]
player_sets = [projections_to_players(projection_set) for projection_set in projection_sets]

for player_set in player_sets:
    optimizer.load_players(player_set)
    for lineup in optimizer.optimize(lineups_per_projection_set):
        wanted_lineups.append(lineup)
```

**Comment by holmes72** [comment]
I made the change.  Lots of little changes...here's the overview:
- Extend player class to include "position" (mapping to the Position column from the DK salaries download) and not just a list of roster positions
- Add a new rule to rules.py: copy RestrictPositionsForOpposingTeam and make changes to only look at the new player.position property

This still didn't make a much better set of lineups.  But to @sansbacon 's point, you're only as good as your projections.
