### ISSUE TITLE
How to speed up to generate 150 lineups?

### ISSUE THREAD

**Issue by JoeAndrei** [DimaKudosh/pydfs-lineup-optimizer#240]
Hi.
Greetings.
I have tried to generate 150 lineups.
It take 2 minutes.
Is there a way to speed up to generate 150 lineups.
Please help me.
Thanks

**Comment by sansbacon** [comment]
Another technique you can use to speed up performance is to break up the optimization into chunks. So, say you want 150 lineups, I would generate 15 different sets of projections for various scenarios and then generate 10 optimal lineup per projection set. This will avoid the slowdown you see when trying to generate 150 lineups at the same time. This approach is most fruitful in sports that have wide ranges of outcomes due to the nature of the sport (baseball, hockey) or how gamescript can affect usage (NFL). I think it applies less in NBA, where mean projections tend to be more accurate, but there is still enough variability that using the ```randomize``` feature with say 10% noise will give you a diverse set of lineups.

**Comment by JoeAndrei** [comment]
Hi, Sansbacon.
How are you?
Thank you for your helping me.
Let me try with your ways.

**Comment by donlaur** [comment]
I would also suggest using the technique in the support docs.

https://pydfs-lineup-optimizer.readthedocs.io/en/latest/performance-and-optimization.html
In this case a good approach is to remove from optimization players with
small fppg value and big salary.

I also reduce the players in the player pool that have no shot of being in
the optimal solved lineup.
The efficiency / value is good but I also exclude players with a projection
under say 3 fp in most sports.
Even if someone is $3K a projection of 3 fp, they are unlikely to be in the
optimal lineup in a classic slate.
I wouldn't do that in a showdown or single game, the player pool isn't high
enough.
You can also change efficiency / value based on position.
DST getting or being projected as 3 fp or 1-2x might be fine.
A position like QB needs to be higher.  Have different levels based on the
total player pool and the positions.

That is basically the efficiency but I do this on the frontend before I
even send the player pool so that my player pool of 500 isn't sent, it is
usually only 100-200, which reduces the JSON sent to the
optimizer backend from the URL endpoint.
That removes the injured, inactives, people who do not regularly get
playing time, if your projections are solid.
Usually ends up greatly reducing the time to produce 150 lineups.

**Comment by JoeAndrei** [comment]
Thanks for your helping me.
