### ISSUE TITLE
FanDuel Basketball drop lowest score update?

### ISSUE THREAD

**Issue by trustylogic** [DimaKudosh/pydfs-lineup-optimizer#34]
Hello,

First, I would like to say thank you so much for creating this :)

I was wonder, will there be an update for FanDuel Basketball as they have changed their rules where the lowest score in your lineup is dropped. 

Thanks.

**Comment by DimaKudosh** [comment]
Hi, I'm not sure what changes I can make for this, fd drops lowest score after contest finish, so we can't add any constraint for this because we don't know how much points each player will score. We still need to have best optimal lineup for maximizing our chances. If you mean that you want to select cheapest player for maximizing budget for other 8 players, you can simply lock cheapest player in lineup and then run optimizer.

**Comment by trustylogic** [comment]
Fair enough... Perhaps when the lineups are outputted, the total does not include the lowest score? Ex:
If the total score is 300 points and the player with the lowest score is 18.5, then the total points will show: 281.5 ??? And maybe have an option to show the lowest score that "potentially" be removed?

Just a thought. Thanks.
