### ISSUE TITLE
Linear Programming Question

### ISSUE THREAD

**Issue by mcarroll316** [DimaKudosh/pydfs-lineup-optimizer#391]
Not a data scientist and having trouble getting my mind around how LP processes things. 

Example:
With a player pool of ~200, I can request a single lineup and that is returned <1 second, but 150 takes 1.5 minutes. The part I struggle understanding is how it can quickly discover the optimal lineup without having all the millions/billions of lineup combinations calculated. Wouldn't it need all combinations to know which one is the optimal? If so, why wouldn't the top 150 be quickly available?

Love the optimizer solution, by the way. Impressive.

**Comment by DimaKudosh** [comment]
This is hard, actually, this library doesn't implement LP algorithms, it's just a wrapper suitable for DFS for the PuLP library that is also a wrapper for most popular LP solvers and these solvers implement different types of algorithms. As I remember default solver implements a [branch and cut](https://en.wikipedia.org/wiki/Branch_and_cut) algorithm.

Generating of the first lineup is faster because it has fewer constraints, after generating every new lineup I add at least one new constraint to a model, but it can be more depending on what exposures/features you set up.
