### ISSUE TITLE
NBA Draftkings Showdown

### ISSUE THREAD

**Issue by wawegner** [DimaKudosh/pydfs-lineup-optimizer#61]
The exposure limits for NBA Draftkings showdown (and likely other showdown types with a captain) don't work as one may think.  I believe the max exposure allows for a player at each position captain and utility.  Is it possible we can have a limiting factor on each?

**Comment by DimaKudosh** [comment]
DraftKings captain mode of optimizer creates separate players for captain and util positions as well as DraftKings do when export players. So max exposure is set twice for captain and util players. I'm not sure that they should be joined, because in this case is not clear what exposure we should use if different exposures set for captain and util and how we can set exposure in csv if it has 2 rows for player.

**Comment by wawegner** [comment]
Can we set exposure by player Id instead of name? This would allow maximum customization

**Comment by DimaKudosh** [comment]
It's not clear what do you mean, can you provide more details?

**Comment by wawegner** [comment]
Sorry. On the csv import each player has a name and an associated player id that they are imported with. The number in parentheses. 

If we set out max exposures using the player Id we can distinguish between the max exposure of a captain and a utility player since the player id is different by position.

**Comment by DimaKudosh** [comment]
How do you set exposure in your code? Do you use `get_player_by_name` method and then set `max_exposure` attribute for returned player?

**Comment by wawegner** [comment]
I use the get player by name.

**Comment by DimaKudosh** [comment]
I will add `get_player_by_id` method to optimizer that search player by id.

**Comment by wawegner** [comment]
you rock.
